/** 音频节点音色库：百炼 CosyVoice v3-flash 系统预置 + 复刻音色 */

export const AUDIO_PROMPT_MAX_CHARS = 50_000;

export type AudioVoiceTab = "library" | "mine" | "favorite";
export type AudioVoiceKind = "library" | "cloned";

export interface AudioVoiceItem {
  id: string;
  /** 展示名：官方「特质」 */
  name: string;
  /** 小字：年龄 · 语言 */
  lang: string;
  gender: string;
  /** 百炼合成用的 voice 参数 */
  voiceId: string;
  /** library=系统预置；cloned=用户复刻 */
  kind: AudioVoiceKind;
  /** 合成模型：预置用 v3-flash，复刻用 v3.5-plus */
  ttsModel: string;
  /** 所属 Tab */
  tabs: AudioVoiceTab[];
  /** 复刻音色本地主键（收藏/删除用） */
  cloneId?: string;
  favorite?: boolean;
}

/** 系统预置音色（与后端 /api/v1/voices 对齐，来源 cosyvoice-v3-flash 官方列表） */
export const AUDIO_VOICE_CATALOG: AudioVoiceItem[] = [
  {
    id: "longanyang",
    name: "阳光大男孩",
    lang: "20~30岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longanyang",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library", "favorite"],
  },
  {
    id: "longanhuan_v3",
    name: "欢脱元气女（多方言）",
    lang: "20~30岁 · 中文（普通话、广东话、东北话、河南话、湖南话、陕西话、山东话、四川话、安徽话）、英文",
    gender: "女",
    voiceId: "longanhuan_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanhuan",
    name: "欢脱元气女",
    lang: "20~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanhuan",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longhuhu_v3",
    name: "天真烂漫女童",
    lang: "6~10岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longhuhu_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longpaopao_v3",
    name: "飞天泡泡音",
    lang: "6~15岁 · 中文（普通话）、英文",
    gender: "",
    voiceId: "longpaopao_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longjielidou_v3",
    name: "阳光顽皮男",
    lang: "10岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longjielidou_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longxian_v3",
    name: "豪放可爱女",
    lang: "12岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longxian_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longling_v3",
    name: "稚气呆板女",
    lang: "10岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longling_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longshanshan_v3",
    name: "戏剧化童声",
    lang: "6~15岁 · 中文（普通话）、英文",
    gender: "",
    voiceId: "longshanshan_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longniuniu_v3",
    name: "阳光男童声",
    lang: "6~15岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longniuniu_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longjiaxin_v3",
    name: "优雅粤语女",
    lang: "30~35岁 · 中文（粤语）、英文",
    gender: "女",
    voiceId: "longjiaxin_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longjiayi_v3",
    name: "知性粤语女",
    lang: "25~30岁 · 中文（粤语）、英文",
    gender: "女",
    voiceId: "longjiayi_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanyue_v3",
    name: "欢脱粤语男",
    lang: "25~35岁 · 中文（粤语）、英文",
    gender: "男",
    voiceId: "longanyue_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longlaotie_v3",
    name: "东北直率男",
    lang: "25~30岁 · 中文（东北话）、英文",
    gender: "男",
    voiceId: "longlaotie_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longshange_v3",
    name: "原味陕北男",
    lang: "25~35岁 · 中文（陕西话）、英文",
    gender: "男",
    voiceId: "longshange_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanmin_v3",
    name: "清纯萝莉女",
    lang: "18~25岁 · 中文（闽南话）、英文",
    gender: "女",
    voiceId: "longanmin_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongkyong_v3",
    name: "韩语女",
    lang: "25~30岁 · 韩语",
    gender: "女",
    voiceId: "loongkyong_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongriko_v3",
    name: "二次元霓虹女",
    lang: "18~25岁 · 日语",
    gender: "女",
    voiceId: "loongriko_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongtomoka_v3",
    name: "日语女",
    lang: "30~35岁 · 日语",
    gender: "女",
    voiceId: "loongtomoka_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongabby_v3",
    name: "美式英文女",
    lang: "30~35岁 · 美式英语",
    gender: "女",
    voiceId: "loongabby_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongandy_v3",
    name: "美式英文男",
    lang: "30~35岁 · 美式英语",
    gender: "男",
    voiceId: "loongandy_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongannie_v3",
    name: "美式英文女",
    lang: "30~35岁 · 美式英语",
    gender: "女",
    voiceId: "loongannie_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongava_v3",
    name: "美式英文女",
    lang: "35~40岁 · 美式英语",
    gender: "女",
    voiceId: "loongava_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongbeth_v3",
    name: "美式英文女",
    lang: "35~40岁 · 美式英语",
    gender: "女",
    voiceId: "loongbeth_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongbetty_v3",
    name: "美式英文女",
    lang: "35~40岁 · 美式英语",
    gender: "女",
    voiceId: "loongbetty_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongcally_v3",
    name: "美式英文女",
    lang: "25~30岁 · 美式英语",
    gender: "女",
    voiceId: "loongcally_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongcindy_v3",
    name: "美式英文女",
    lang: "30~35岁 · 美式英语",
    gender: "女",
    voiceId: "loongcindy_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongdavid_v3",
    name: "美式英文男",
    lang: "35~40岁 · 美式英语",
    gender: "男",
    voiceId: "loongdavid_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongdonna_v3",
    name: "美式英文女",
    lang: "35~40岁 · 美式英语",
    gender: "女",
    voiceId: "loongdonna_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongemily_v3",
    name: "英式英文女",
    lang: "35~40岁 · 英式英语",
    gender: "女",
    voiceId: "loongemily_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongeric_v3",
    name: "英式英文男",
    lang: "35~40岁 · 英式英语",
    gender: "男",
    voiceId: "loongeric_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongluna_v3",
    name: "英式英文女",
    lang: "35~40岁 · 英式英语",
    gender: "女",
    voiceId: "loongluna_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongluca_v3",
    name: "英式英文男",
    lang: "25~30岁 · 英式英语",
    gender: "男",
    voiceId: "loongluca_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongtomoya_v3",
    name: "日语男",
    lang: "30~35岁 · 日语",
    gender: "男",
    voiceId: "loongtomoya_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongyuuna_v3",
    name: "日语女",
    lang: "18~25岁 · 日语",
    gender: "女",
    voiceId: "loongyuuna_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongyuuma_v3",
    name: "日语男",
    lang: "20~25岁 · 日语",
    gender: "男",
    voiceId: "loongyuuma_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongjihun_v3",
    name: "韩语男",
    lang: "25~30岁 · 韩语",
    gender: "男",
    voiceId: "loongjihun_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongindah_v3",
    name: "印尼女",
    lang: "22~27岁 · 印尼语",
    gender: "女",
    voiceId: "loongindah_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longfei_v3",
    name: "热血磁性男",
    lang: "30~35岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longfei_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyingxiao_v3",
    name: "清甜推销女",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyingxiao_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyingxun_v3",
    name: "年轻青涩男",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longyingxun_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyingjing_v3",
    name: "低调冷静女",
    lang: "25~35岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyingjing_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyingling_v3",
    name: "温和共情女",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyingling_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyingtao_v3",
    name: "温柔淡定女",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyingtao_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longxiaochun_v3",
    name: "知性积极女",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longxiaochun_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library", "favorite"],
  },
  {
    id: "longxiaoxia_v3",
    name: "沉稳权威女",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longxiaoxia_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyumi_v3",
    name: "正经青年女",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyumi_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanyun_v3",
    name: "居家暖男",
    lang: "30~35岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longanyun_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanwen_v3",
    name: "优雅知性女",
    lang: "25~35岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanwen_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanli_v3",
    name: "利落从容女",
    lang: "25~35岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanli_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanlang_v3",
    name: "清爽利落男",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longanlang_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyingmu_v3",
    name: "优雅知性女",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyingmu_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longantai_v3",
    name: "嗲甜台湾女",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longantai_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longhua_v3",
    name: "元气甜美女",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longhua_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library", "favorite"],
  },
  {
    id: "longcheng_v3",
    name: "智慧青年男",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longcheng_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longze_v3",
    name: "温暖元气男",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longze_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longzhe_v3",
    name: "呆板大暖男",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longzhe_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyan_v3",
    name: "温暖春风女",
    lang: "30~35岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyan_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longxing_v3",
    name: "温婉邻家女",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longxing_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longtian_v3",
    name: "磁性理智男",
    lang: "30~35岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longtian_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longwan_v3",
    name: "细腻柔声女",
    lang: "20~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longwan_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longqiang_v3",
    name: "浪漫风情女",
    lang: "30~35岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longqiang_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longfeifei_v3",
    name: "甜美娇气女",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longfeifei_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longhao_v3",
    name: "多情忧郁男",
    lang: "30~35岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longhao_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanrou_v3",
    name: "温柔闺蜜女",
    lang: "20~35岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanrou_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longhan_v3",
    name: "温暖痴情男",
    lang: "30~35岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longhan_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanzhi_v3",
    name: "睿智轻熟男",
    lang: "25~35岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longanzhi_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanling_v3",
    name: "思维灵动女",
    lang: "20~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanling_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanya_v3",
    name: "高雅气质女",
    lang: "25~35岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanya_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanqin_v3",
    name: "亲和活泼女",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanqin_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longmiao_v3",
    name: "抑扬顿挫女",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longmiao_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longsanshu_v3",
    name: "沉稳质感男",
    lang: "25~45岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longsanshu_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyuan_v3",
    name: "温暖治愈女",
    lang: "35~40岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyuan_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyue_v3",
    name: "温暖磁性女",
    lang: "30~35岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longyue_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longxiu_v3",
    name: "博才说书男",
    lang: "25~35岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longxiu_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longnan_v3",
    name: "睿智青年男",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longnan_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longwanjun_v3",
    name: "细腻柔声女",
    lang: "20~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longwanjun_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longyichen_v3",
    name: "洒脱活力男",
    lang: "20~30岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longyichen_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longlaobo_v3",
    name: "沧桑岁月爷",
    lang: "60岁以上 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longlaobo_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longlaoyi_v3",
    name: "烟火从容阿姨",
    lang: "60岁以上 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longlaoyi_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longjiqi_v3",
    name: "呆萌机器人",
    lang: "20~30岁 · 中文（普通话）、英文",
    gender: "",
    voiceId: "longjiqi_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longhouge_v3",
    name: "经典猴哥",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longhouge_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longdaiyu_v3",
    name: "娇率才女音",
    lang: "15~25岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longdaiyu_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanran_v3",
    name: "活泼质感女",
    lang: "30~40岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanran_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longanxuan_v3",
    name: "经典直播女",
    lang: "30~40岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "longanxuan_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longshuo_v3",
    name: "博才干练男",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longshuo_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "longshu_v3",
    name: "沉稳青年男",
    lang: "20~25岁 · 中文（普通话）、英文",
    gender: "男",
    voiceId: "longshu_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
  {
    id: "loongbella_v3",
    name: "精准干练女",
    lang: "25~30岁 · 中文（普通话）、英文",
    gender: "女",
    voiceId: "loongbella_v3",
    kind: "library",
    ttsModel: "cosyvoice-v3-flash",
    tabs: ["library"],
  },
];

export const DEFAULT_AUDIO_VOICE_STYLE = "元气甜美女";

export const DEFAULT_AUDIO_VOICE =
  AUDIO_VOICE_CATALOG.find((v) => v.name === DEFAULT_AUDIO_VOICE_STYLE) ??
  AUDIO_VOICE_CATALOG[0]!;

/** 兼容旧短列表与任意库内音色名 */
export function normalizeAudioVoiceStyle(raw: unknown): string {
  const s = typeof raw === "string" ? raw.trim() : "";
  if (!s) return DEFAULT_AUDIO_VOICE_STYLE;
  if (AUDIO_VOICE_CATALOG.some((v) => v.name === s)) return s;
  // 兼容旧展示名 → 新特质名
  const legacy: Record<string, string> = {
    少女音色: "元气甜美女",
    青涩青年音色: "阳光大男孩",
    精英青年音色: "智慧青年男",
    霸道青年音色: "睿智青年男",
    青年大学生音色: "沉稳青年男",
    御姐音色: "知性积极女",
    少年音色: "阳光顽皮男",
    成熟男声: "博才干练男",
  };
  if (legacy[s]) return legacy[s];
  return s;
}

export function findAudioVoiceByName(name: string): AudioVoiceItem | undefined {
  const normalized = normalizeAudioVoiceStyle(name);
  return AUDIO_VOICE_CATALOG.find((v) => v.name === normalized || v.name === name);
}

export function findAudioVoiceById(id: string): AudioVoiceItem | undefined {
  return AUDIO_VOICE_CATALOG.find((v) => v.id === id || v.voiceId === id);
}

/** 从节点 params 解析当前音色（优先 voiceId） */
export function resolveAudioVoiceFromParams(params: Record<string, unknown> | undefined): {
  label: string;
  voiceId: string;
  kind: AudioVoiceKind;
  ttsModel: string;
} {
  const label = normalizeAudioVoiceStyle(params?.voiceStyleLabel);
  const voiceId = String(params?.voiceId || params?.voice_id || "").trim();
  const kind = (String(params?.voiceKind || "").trim() || "library") as AudioVoiceKind;
  const ttsModel = String(params?.ttsModel || "").trim();
  if (voiceId) {
    const byId = findAudioVoiceById(voiceId);
    return {
      label: byId?.name || label,
      voiceId,
      kind: kind === "cloned" ? "cloned" : "library",
      ttsModel:
        ttsModel ||
        (kind === "cloned" ? "cosyvoice-v3.5-plus" : byId?.ttsModel || "cosyvoice-v3-flash"),
    };
  }
  const catalog = findAudioVoiceByName(label) || DEFAULT_AUDIO_VOICE;
  return {
    label: catalog.name,
    voiceId: catalog.voiceId,
    kind: "library",
    ttsModel: catalog.ttsModel,
  };
}
