"""百炼 CosyVoice v3-flash 系统预置音色（与官方音色列表对齐）。

展示名用「特质」；小字为「年龄 · 语言」。合成模型固定 cosyvoice-v3-flash。
复刻音色走 cosyvoice-v3.5-plus，不在本列表。
"""

from __future__ import annotations

# 官方预置音色合成模型（v3.5-plus 无系统音色，仅用于声音复刻）
PRESET_TTS_MODEL = "cosyvoice-v3-flash"

COSYVOICE_LIBRARY_VOICES: list[dict] = [
    {
        "id": "longanyang",
        "name": "阳光大男孩",
        "voice_id": "longanyang",
        "lang": "20~30岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanhuan_v3",
        "name": "欢脱元气女（多方言）",
        "voice_id": "longanhuan_v3",
        "lang": "20~30岁 · 中文（普通话、广东话、东北话、河南话、湖南话、陕西话、山东话、四川话、安徽话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanhuan",
        "name": "欢脱元气女",
        "voice_id": "longanhuan",
        "lang": "20~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longhuhu_v3",
        "name": "天真烂漫女童",
        "voice_id": "longhuhu_v3",
        "lang": "6~10岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longpaopao_v3",
        "name": "飞天泡泡音",
        "voice_id": "longpaopao_v3",
        "lang": "6~15岁 · 中文（普通话）、英文",
        "gender": "",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longjielidou_v3",
        "name": "阳光顽皮男",
        "voice_id": "longjielidou_v3",
        "lang": "10岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longxian_v3",
        "name": "豪放可爱女",
        "voice_id": "longxian_v3",
        "lang": "12岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longling_v3",
        "name": "稚气呆板女",
        "voice_id": "longling_v3",
        "lang": "10岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longshanshan_v3",
        "name": "戏剧化童声",
        "voice_id": "longshanshan_v3",
        "lang": "6~15岁 · 中文（普通话）、英文",
        "gender": "",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longniuniu_v3",
        "name": "阳光男童声",
        "voice_id": "longniuniu_v3",
        "lang": "6~15岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longjiaxin_v3",
        "name": "优雅粤语女",
        "voice_id": "longjiaxin_v3",
        "lang": "30~35岁 · 中文（粤语）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longjiayi_v3",
        "name": "知性粤语女",
        "voice_id": "longjiayi_v3",
        "lang": "25~30岁 · 中文（粤语）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanyue_v3",
        "name": "欢脱粤语男",
        "voice_id": "longanyue_v3",
        "lang": "25~35岁 · 中文（粤语）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longlaotie_v3",
        "name": "东北直率男",
        "voice_id": "longlaotie_v3",
        "lang": "25~30岁 · 中文（东北话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longshange_v3",
        "name": "原味陕北男",
        "voice_id": "longshange_v3",
        "lang": "25~35岁 · 中文（陕西话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanmin_v3",
        "name": "清纯萝莉女",
        "voice_id": "longanmin_v3",
        "lang": "18~25岁 · 中文（闽南话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongkyong_v3",
        "name": "韩语女",
        "voice_id": "loongkyong_v3",
        "lang": "25~30岁 · 韩语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongriko_v3",
        "name": "二次元霓虹女",
        "voice_id": "loongriko_v3",
        "lang": "18~25岁 · 日语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongtomoka_v3",
        "name": "日语女",
        "voice_id": "loongtomoka_v3",
        "lang": "30~35岁 · 日语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongabby_v3",
        "name": "美式英文女",
        "voice_id": "loongabby_v3",
        "lang": "30~35岁 · 美式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongandy_v3",
        "name": "美式英文男",
        "voice_id": "loongandy_v3",
        "lang": "30~35岁 · 美式英语",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongannie_v3",
        "name": "美式英文女",
        "voice_id": "loongannie_v3",
        "lang": "30~35岁 · 美式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongava_v3",
        "name": "美式英文女",
        "voice_id": "loongava_v3",
        "lang": "35~40岁 · 美式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongbeth_v3",
        "name": "美式英文女",
        "voice_id": "loongbeth_v3",
        "lang": "35~40岁 · 美式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongbetty_v3",
        "name": "美式英文女",
        "voice_id": "loongbetty_v3",
        "lang": "35~40岁 · 美式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongcally_v3",
        "name": "美式英文女",
        "voice_id": "loongcally_v3",
        "lang": "25~30岁 · 美式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongcindy_v3",
        "name": "美式英文女",
        "voice_id": "loongcindy_v3",
        "lang": "30~35岁 · 美式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongdavid_v3",
        "name": "美式英文男",
        "voice_id": "loongdavid_v3",
        "lang": "35~40岁 · 美式英语",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongdonna_v3",
        "name": "美式英文女",
        "voice_id": "loongdonna_v3",
        "lang": "35~40岁 · 美式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongemily_v3",
        "name": "英式英文女",
        "voice_id": "loongemily_v3",
        "lang": "35~40岁 · 英式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongeric_v3",
        "name": "英式英文男",
        "voice_id": "loongeric_v3",
        "lang": "35~40岁 · 英式英语",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongluna_v3",
        "name": "英式英文女",
        "voice_id": "loongluna_v3",
        "lang": "35~40岁 · 英式英语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongluca_v3",
        "name": "英式英文男",
        "voice_id": "loongluca_v3",
        "lang": "25~30岁 · 英式英语",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongtomoya_v3",
        "name": "日语男",
        "voice_id": "loongtomoya_v3",
        "lang": "30~35岁 · 日语",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongyuuna_v3",
        "name": "日语女",
        "voice_id": "loongyuuna_v3",
        "lang": "18~25岁 · 日语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongyuuma_v3",
        "name": "日语男",
        "voice_id": "loongyuuma_v3",
        "lang": "20~25岁 · 日语",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongjihun_v3",
        "name": "韩语男",
        "voice_id": "loongjihun_v3",
        "lang": "25~30岁 · 韩语",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongindah_v3",
        "name": "印尼女",
        "voice_id": "loongindah_v3",
        "lang": "22~27岁 · 印尼语",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longfei_v3",
        "name": "热血磁性男",
        "voice_id": "longfei_v3",
        "lang": "30~35岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyingxiao_v3",
        "name": "清甜推销女",
        "voice_id": "longyingxiao_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyingxun_v3",
        "name": "年轻青涩男",
        "voice_id": "longyingxun_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyingjing_v3",
        "name": "低调冷静女",
        "voice_id": "longyingjing_v3",
        "lang": "25~35岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyingling_v3",
        "name": "温和共情女",
        "voice_id": "longyingling_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyingtao_v3",
        "name": "温柔淡定女",
        "voice_id": "longyingtao_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longxiaochun_v3",
        "name": "知性积极女",
        "voice_id": "longxiaochun_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longxiaoxia_v3",
        "name": "沉稳权威女",
        "voice_id": "longxiaoxia_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyumi_v3",
        "name": "正经青年女",
        "voice_id": "longyumi_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanyun_v3",
        "name": "居家暖男",
        "voice_id": "longanyun_v3",
        "lang": "30~35岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanwen_v3",
        "name": "优雅知性女",
        "voice_id": "longanwen_v3",
        "lang": "25~35岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanli_v3",
        "name": "利落从容女",
        "voice_id": "longanli_v3",
        "lang": "25~35岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanlang_v3",
        "name": "清爽利落男",
        "voice_id": "longanlang_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyingmu_v3",
        "name": "优雅知性女",
        "voice_id": "longyingmu_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longantai_v3",
        "name": "嗲甜台湾女",
        "voice_id": "longantai_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longhua_v3",
        "name": "元气甜美女",
        "voice_id": "longhua_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longcheng_v3",
        "name": "智慧青年男",
        "voice_id": "longcheng_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longze_v3",
        "name": "温暖元气男",
        "voice_id": "longze_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longzhe_v3",
        "name": "呆板大暖男",
        "voice_id": "longzhe_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyan_v3",
        "name": "温暖春风女",
        "voice_id": "longyan_v3",
        "lang": "30~35岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longxing_v3",
        "name": "温婉邻家女",
        "voice_id": "longxing_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longtian_v3",
        "name": "磁性理智男",
        "voice_id": "longtian_v3",
        "lang": "30~35岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longwan_v3",
        "name": "细腻柔声女",
        "voice_id": "longwan_v3",
        "lang": "20~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longqiang_v3",
        "name": "浪漫风情女",
        "voice_id": "longqiang_v3",
        "lang": "30~35岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longfeifei_v3",
        "name": "甜美娇气女",
        "voice_id": "longfeifei_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longhao_v3",
        "name": "多情忧郁男",
        "voice_id": "longhao_v3",
        "lang": "30~35岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanrou_v3",
        "name": "温柔闺蜜女",
        "voice_id": "longanrou_v3",
        "lang": "20~35岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longhan_v3",
        "name": "温暖痴情男",
        "voice_id": "longhan_v3",
        "lang": "30~35岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanzhi_v3",
        "name": "睿智轻熟男",
        "voice_id": "longanzhi_v3",
        "lang": "25~35岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanling_v3",
        "name": "思维灵动女",
        "voice_id": "longanling_v3",
        "lang": "20~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanya_v3",
        "name": "高雅气质女",
        "voice_id": "longanya_v3",
        "lang": "25~35岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanqin_v3",
        "name": "亲和活泼女",
        "voice_id": "longanqin_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longmiao_v3",
        "name": "抑扬顿挫女",
        "voice_id": "longmiao_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longsanshu_v3",
        "name": "沉稳质感男",
        "voice_id": "longsanshu_v3",
        "lang": "25~45岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyuan_v3",
        "name": "温暖治愈女",
        "voice_id": "longyuan_v3",
        "lang": "35~40岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyue_v3",
        "name": "温暖磁性女",
        "voice_id": "longyue_v3",
        "lang": "30~35岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longxiu_v3",
        "name": "博才说书男",
        "voice_id": "longxiu_v3",
        "lang": "25~35岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longnan_v3",
        "name": "睿智青年男",
        "voice_id": "longnan_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longwanjun_v3",
        "name": "细腻柔声女",
        "voice_id": "longwanjun_v3",
        "lang": "20~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longyichen_v3",
        "name": "洒脱活力男",
        "voice_id": "longyichen_v3",
        "lang": "20~30岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longlaobo_v3",
        "name": "沧桑岁月爷",
        "voice_id": "longlaobo_v3",
        "lang": "60岁以上 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longlaoyi_v3",
        "name": "烟火从容阿姨",
        "voice_id": "longlaoyi_v3",
        "lang": "60岁以上 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longjiqi_v3",
        "name": "呆萌机器人",
        "voice_id": "longjiqi_v3",
        "lang": "20~30岁 · 中文（普通话）、英文",
        "gender": "",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longhouge_v3",
        "name": "经典猴哥",
        "voice_id": "longhouge_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longdaiyu_v3",
        "name": "娇率才女音",
        "voice_id": "longdaiyu_v3",
        "lang": "15~25岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanran_v3",
        "name": "活泼质感女",
        "voice_id": "longanran_v3",
        "lang": "30~40岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longanxuan_v3",
        "name": "经典直播女",
        "voice_id": "longanxuan_v3",
        "lang": "30~40岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longshuo_v3",
        "name": "博才干练男",
        "voice_id": "longshuo_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "longshu_v3",
        "name": "沉稳青年男",
        "voice_id": "longshu_v3",
        "lang": "20~25岁 · 中文（普通话）、英文",
        "gender": "男",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
    {
        "id": "loongbella_v3",
        "name": "精准干练女",
        "voice_id": "loongbella_v3",
        "lang": "25~30岁 · 中文（普通话）、英文",
        "gender": "女",
        "kind": "library",
        "tts_model": PRESET_TTS_MODEL,
    },
]

def library_voices() -> list[dict]:
    """返回系统预置音色副本（供 /api/v1/voices）。"""
    return [dict(v) for v in COSYVOICE_LIBRARY_VOICES]
