from fastapi import APIRouter

from . import admin_permissions as admin_perms_api, auth_settings, credit_activities as admin_credit_activities, credits as admin_credits, discover_settings, footer_settings, generation_logs, homepage_settings, invite_campaigns as admin_invite_campaigns, jobs, material_library as admin_material_library, me, model_providers, models, pricing, projects, prompt_config, prompt_templates, recharge_orders, recharge_tiers as admin_recharge_tiers, register_bonus as admin_register_bonus, sensitive_words as admin_sensitive_words, skill_docs as admin_skill_docs, skills_manage as admin_skills_manage, stats, storage_settings as admin_storage_settings, subscriptions as admin_subscriptions, users, workflow_publications_manage as admin_workflow_pubs

router = APIRouter()
router.include_router(me.router)
router.include_router(admin_perms_api.router)
router.include_router(auth_settings.router)
router.include_router(admin_register_bonus.router)
router.include_router(homepage_settings.router)
router.include_router(discover_settings.router)
router.include_router(admin_material_library.router)
router.include_router(footer_settings.router)
router.include_router(admin_skill_docs.router)
router.include_router(admin_skills_manage.router)
router.include_router(admin_workflow_pubs.router)
router.include_router(stats.router)
router.include_router(jobs.router)
router.include_router(generation_logs.router)
router.include_router(models.router)
router.include_router(model_providers.router)
router.include_router(pricing.router)
router.include_router(admin_credits.router)
router.include_router(admin_credit_activities.router)
router.include_router(admin_invite_campaigns.router)
router.include_router(admin_subscriptions.router)
router.include_router(admin_recharge_tiers.router)
router.include_router(admin_storage_settings.router)
router.include_router(recharge_orders.router, prefix="/recharge-orders", tags=["recharge-orders"])
router.include_router(projects.router)
router.include_router(users.router)
router.include_router(prompt_templates.router)
router.include_router(prompt_config.router)
router.include_router(admin_sensitive_words.router)
